### ISSUE TITLE
how to implement pagination?

### ISSUE THREAD

**Issue by guvanch07** [kosukesaigusa/geoflutterfire_plus#176]
I would like to do pagination by adding limit and startDocument queries but didn't work

**Comment by tiltmaster** [comment]
thats legit my question lol, as im currently facing an issue when filtering by geopoints.

**Comment by kosukesaigusa** [comment]
Hello @guvanch07 @tiltmaster!

Thank you for your comments!

As you can see in README, currently `limit` and `orderBy` queries are not supported because of the geo hash query algorithm and Cloud Firestore query limitations. Unfortunately, for the same reason, pagination query is not possible! (We can not order by the query result, so we can not get paginated result.)

If you have any ideas, PRs are always welcome!

Thank you!

**Comment by tiltmaster** [comment]
> Hello @guvanch07 @tiltmaster!
> 
> Thank you for your comments!
> 
> As you can see in README, currently `limit` and `orderBy` queries are not supported because of the geo hash query algorithm and Cloud Firestore query limitations. Unfortunately, for the same reason, pagination query is not possible! (We can not order by the query result, so we can not get paginated result.)
> 
> If you have any ideas, PRs are always welcome!
> 
> Thank you!

Much appreciated,  honestly im just tired of how limited firebase is, a Migration is definitely now in order to supabase.

Thanks.
